build: off

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
cache:
- c:\sr

install:
- ps: |
    Write-Host "Installing Azure storage emulator..." -ForegroundColor Cyan
    Write-Host "Downloading..."
    $msiPath = "$env:TEMP\MicrosoftAzureStorageEmulator.msi"
    (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/1/F/C/1FCF23A3-BBD8-4F50-B5C2-E382F14A2AAD/MicrosoftAzureStorageEmulator.msi', $msiPath)
    Write-Host "Installing..."
    cmd /c start /wait msiexec /i "$msiPath" /q
    del $msiPath
    Write-Host "Installed Azure storage emulator" -ForegroundColor Green
# Make sure GHC is in STACK_ROOT
- ps: |
    mkdir c:\sr
    echo "local-programs-path: c:\sr\programs" > c:\sr\config.yaml

test_script:
- stack setup > nul
# init the storage emulator
- "\"C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Storage Emulator\\AzureStorageEmulator.exe\" init"
- "\"C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Storage Emulator\\AzureStorageEmulator.exe\" start"
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal test -j 8
- "\"C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Storage Emulator\\AzureStorageEmulator.exe\" stop"
